version: "3"
services:
  terraform:
    build: 
      context: ./terraform
      args:
        ARG_AWS_ACCESS_KEY_ID: SUA_KEY_ID
        ARG_AWS_SECRET_ACCESS_KEY: SUA_SECRET_ACCESS_KEY
        ARG_DEFAULT_REGION: sa-east-1
    #command: "terraform plan"
    command: "terraform apply -no-color -auto-approve"
    #command: "terraform destroy -no-color -auto-approve"
    volumes:
      - ./terraform/output:/output
